// <auto-generated />
using System;
using BabyNamePicker.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BabyNamePicker.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721193052_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("BabyNameNickname", b =>
                {
                    b.Property<int>("NamesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NicknamesId")
                        .HasColumnType("INTEGER");

                    b.HasKey("NamesId", "NicknamesId");

                    b.HasIndex("NicknamesId");

                    b.ToTable("BabyNameNickname");
                });

            modelBuilder.Entity("BabyNamePicker.Models.BabyName", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaleShare")
                        .HasPrecision(5, 4)
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Names");
                });

            modelBuilder.Entity("BabyNamePicker.Models.NameYearStat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rank")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sex")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("NameId", "Year", "Sex")
                        .IsUnique();

                    b.ToTable("NameYearStats");
                });

            modelBuilder.Entity("BabyNamePicker.Models.Nickname", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("Nicknames");
                });

            modelBuilder.Entity("BabyNameNickname", b =>
                {
                    b.HasOne("BabyNamePicker.Models.BabyName", null)
                        .WithMany()
                        .HasForeignKey("NamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BabyNamePicker.Models.Nickname", null)
                        .WithMany()
                        .HasForeignKey("NicknamesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BabyNamePicker.Models.NameYearStat", b =>
                {
                    b.HasOne("BabyNamePicker.Models.BabyName", "Name")
                        .WithMany("YearStats")
                        .HasForeignKey("NameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Name");
                });

            modelBuilder.Entity("BabyNamePicker.Models.BabyName", b =>
                {
                    b.Navigation("YearStats");
                });
#pragma warning restore 612, 618
        }
    }
}
